mode := release

AR := ar
CC := gcc
AS := nasm

STATIC_CFLAGS := -Iinclude -Wno-discarded-qualifiers
STATIC_CFLAGS_DEBUG := -g -O0 -DKORE_DEBUG
STATIC_CFLAGS_RELEASE := -O3 -DKORE_RELEASE

STATIC_PATH_DEBUG := debug/
STATIC_PATH_RELEASE := release/

STATIC_PATH_SRC := src/
STATIC_PATH_BIN := bin/
STATIC_PATH_OBJ := obj/

STATIC_PATH_X86 := x86/
STATIC_PATH_X86_64 := x86_64/

STATIC_PATH_LINUX := linux/
STATIC_PATH_WINDOWS := windows/

STATIC_PATH_CDECL := cdecl/
STATIC_PATH_MICROSOFT_X64 := Microsoft_x64/
STATIC_PATH_SYSTEM_V_AMD64 := System_V_AMD64/

PATH_SRC := $(STATIC_PATH_SRC)
PATH_CDECL := $(STATIC_PATH_SRC)$(STATIC_PATH_X86)$(STATIC_PATH_CDECL)
PATH_MICROSOFT_X64 := $(STATIC_PATH_SRC)$(STATIC_PATH_X86_64)$(STATIC_PATH_MICROSOFT_X64)
PATH_SYSTEM_V_AMD64 := $(STATIC_PATH_SRC)$(STATIC_PATH_X86_64)$(STATIC_PATH_SYSTEM_V_AMD64)

ifeq ($(mode),release)

CFLAGS := $(STATIC_CFLAGS) $(STATIC_CFLAGS_RELEASE)
PATH_BIN := $(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)
PATH_OBJ := $(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ)

else

CFLAGS := $(STATIC_CFLAGS) $(STATIC_CFLAGS_DEBUG)
PATH_BIN := $(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)
PATH_OBJ := $(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ)

endif

PATH_OBJ_X86_LINUX := $(PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_LINUX)
PATH_OBJ_X86_WINDOWS := $(PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_WINDOWS)
PATH_OBJ_X86_64_LINUX := $(PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_LINUX)
PATH_OBJ_X86_64_WINDOWS := $(PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_WINDOWS)

binary := $(PATH_BIN)libkore.a