sys := LINUX
arch := X86_64
mode := release

use_std := false
sys_use_std := false

AR := ar
CC := gcc
AS := nasm

STATIC_AFLAGS := 
STATIC_AFLAGS_DEBUG := -g
STATIC_AFLAGS_RELEASE :=

STATIC_CFLAGS := -DKORE_OS_$(sys) -DKORE_ARCH_$(arch) -Iinclude -Wno-discarded-qualifiers 
STATIC_CFLAGS_DEBUG := -g -O0 -DKORE_DEBUG
STATIC_CFLAGS_RELEASE := -O3 -DKORE_RELEASE

STATIC_PATH_DEBUG := debug/
STATIC_PATH_RELEASE := release/

STATIC_PATH_SRC := src/
STATIC_PATH_BIN := bin/
STATIC_PATH_OBJ := obj/

STATIC_PATH_X86 := x86/
STATIC_PATH_X86_64 := x86_64/

STATIC_PATH_LINUX := linux/
STATIC_PATH_WINDOWS := windows/

STATIC_PATH_CDECL := cdecl/
STATIC_PATH_MICROSOFT_X64 := Microsoft_x64/
STATIC_PATH_SYSTEM_V_AMD64 := System_V_AMD64/

PATH_SRC := $(STATIC_PATH_SRC)
PATH_CDECL := $(STATIC_PATH_SRC)$(STATIC_PATH_X86)$(STATIC_PATH_CDECL)
PATH_MICROSOFT_X64 := $(STATIC_PATH_SRC)$(STATIC_PATH_X86_64)$(STATIC_PATH_MICROSOFT_X64)
PATH_SYSTEM_V_AMD64 := $(STATIC_PATH_SRC)$(STATIC_PATH_X86_64)$(STATIC_PATH_SYSTEM_V_AMD64)

ifeq ($(mode),release)

AFLAGS := $(STATIC_AFLAGS) $(STATIC_AFLAGS_RELEASE)
CFLAGS := $(STATIC_CFLAGS) $(STATIC_CFLAGS_RELEASE)
PATH_BIN := $(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)
PATH_OBJ := $(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ)

else

AFLAGS := $(STATIC_AFLAGS) $(STATIC_AFLAGS_DEBUG)
CFLAGS := $(STATIC_CFLAGS) $(STATIC_CFLAGS_DEBUG)
PATH_BIN := $(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)
PATH_OBJ := $(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ)

endif

ifneq ($(use_std), false)
CFLAGS := $(CFLAGS) -DKORE_USE_STD
endif

ifneq ($(sys_use_std), false)
CFLAGS := $(CFLAGS) -DKORE_SYS_USE_STD
endif

PATH_OBJ_X86_LINUX := $(PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_LINUX)
PATH_OBJ_X86_WINDOWS := $(PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_WINDOWS)
PATH_OBJ_X86_64_LINUX := $(PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_LINUX)
PATH_OBJ_X86_64_WINDOWS := $(PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_WINDOWS)

FILES_SRC := $(wildcard $(PATH_SRC)*.c)
FILES_CDECL := $(wildcard $(PATH_CDECL)*.s)
FILES_MICROSOFT_X64 := $(wildcard $(PATH_MICROSOFT_X64)*.s)
FILES_SYSTEM_V_AMD64 := $(wildcard $(PATH_SYSTEM_V_AMD64)*.s)

OBJ_FILES_SRC := $(patsubst $(PATH_SRC)%.c,$(PATH_OBJ)%.o,$(FILES_SRC))
OBJ_FILES_X86_LINUX := $(patsubst $(PATH_CDECL)%.s,$(PATH_OBJ_X86_LINUX)%.o,$(FILES_CDECL))
OBJ_FILES_X86_WINDOWS := $(patsubst $(PATH_CDECL)%.s,$(PATH_OBJ_X86_WINDOWS)%.o,$(FILES_CDECL))
OBJ_FILES_X86_64_LINUX := $(patsubst $(PATH_SYSTEM_V_AMD64)%.s,$(PATH_OBJ_X86_64_LINUX)%.o,$(FILES_SYSTEM_V_AMD64))
OBJ_FILES_X86_64_WINDOWS := $(patsubst $(PATH_MICROSOFT_X64)%.s,$(PATH_OBJ_X86_64_WINDOWS)%.o,$(FILES_MICROSOFT_X64))