WIN32_PATH_BIN_RELEASE := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE))
WIN32_PATH_OBJ_RELEASE := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ))
WIN32_PATH_OBJ_RELEASE_X86_LINUX := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_LINUX))
WIN32_PATH_OBJ_RELEASE_X86_WINDOWS := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_WINDOWS))
WIN32_PATH_OBJ_RELEASE_X86_64_LINUX := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_LINUX))
WIN32_PATH_OBJ_RELEASE_X86_64_WINDOWS := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_RELEASE)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_WINDOWS))

WIN32_PATH_BIN_DEBUG := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG))
WIN32_PATH_OBJ_DEBUG := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ))
WIN32_PATH_OBJ_DEBUG_X86_LINUX := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_LINUX))
WIN32_PATH_OBJ_DEBUG_X86_WINDOWS := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86)$(STATIC_PATH_WINDOWS))
WIN32_PATH_OBJ_DEBUG_X86_64_LINUX := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_LINUX))
WIN32_PATH_OBJ_DEBUG_X86_64_WINDOWS := $(subst /,\,$(STATIC_PATH_BIN)$(STATIC_PATH_DEBUG)$(STATIC_PATH_OBJ)$(STATIC_PATH_X86_64)$(STATIC_PATH_WINDOWS))

mkdir:
	@md $(WIN32_PATH_OBJ_RELEASE_X86_LINUX)
	@md $(WIN32_PATH_OBJ_RELEASE_X86_WINDOWS)
	@md $(WIN32_PATH_OBJ_RELEASE_X86_64_LINUX)
	@md $(WIN32_PATH_OBJ_RELEASE_X86_64_WINDOWS)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_LINUX)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_WINDOWS)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_64_LINUX)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_64_WINDOWS)
	
clean:
	@rm $(WIN32_PATH_BIN_RELEASE)\*.*
	@rm $(WIN32_PATH_OBJ_RELEASE)\*.*
	@rm $(WIN32_PATH_OBJ_RELEASE_X86_LINUX\)*.*
	@rm $(WIN32_PATH_OBJ_RELEASE_X86_WINDOWS)\*.*
	@rm $(WIN32_PATH_OBJ_RELEASE_X86_64_LINUX)\*.*
	@rm $(WIN32_PATH_OBJ_RELEASE_X86_64_WINDOWS)\*.*
	@rm $(WIN32_PATH_BIN_DEBUG)\*.*
	@rm $(WIN32_PATH_OBJ_DEBUG)\*.*
	@rm $(WIN32_PATH_OBJ_DEBUG_X86_LINUX)\*.*
	@rm $(WIN32_PATH_OBJ_DEBUG_X86_WINDOWS)\*.*
	@rm $(WIN32_PATH_OBJ_DEBUG_X86_64_LINUX)\*.*
	@rm $(WIN32_PATH_OBJ_DEBUG_X86_64_WINDOWS)\*.*
	@md $(WIN32_PATH_OBJ_RELEASE_X86_LINUX)
	@md $(WIN32_PATH_OBJ_RELEASE_X86_WINDOWS)
	@md $(WIN32_PATH_OBJ_RELEASE_X86_64_LINUX)
	@md $(WIN32_PATH_OBJ_RELEASE_X86_64_WINDOWS)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_LINUX)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_WINDOWS)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_64_LINUX)
	@md $(WIN32_PATH_OBJ_DEBUG_X86_64_WINDOWS)